### ISSUE TITLE
Collision with ROS installation: urdfdom clash/ambiguity

### ISSUE THREAD

**Issue by HWiese1980** [rock-learning/bolero#7] opened 2017-08-04 12:05 UTC
With a preinstalled ROS it is not possible to successfully bootstrap BOLeRo. Building urdfdom fails, probably due to some collisions with ROS headers. 

Further investigation of possible options to explicitly set the used dependencies/headers/libraries appear to be necessary. 

Same applies to ApproxIK which also depends on urdfdom and which also fails to build when there is already a ROS installation on the system. 

This happens even if ROS isn't activated (setup.bash *not* sourced).

**Comment by AlexanderFabisch** [comment] 2017-08-04 12:11
ROS should be located at /opt/ros/<version>. Neither CMake macros, nor libraries or headers should be in conflict with BOLeRo unless some LD_LIBRARY_PATH etc. is modified. I could not reproduce the problem on my machine. Could you post relevant environment variables?

**Comment by HWiese1980** [comment] 2017-08-04 12:18
Sure. 

Here's the output of a manual `make` in bolero-dev/control/urdfdom/build: https://pastebin.com/yDAXbw3s

And here is the environment: https://pastebin.com/TE9fvtTA

**Comment by HWiese1980** [comment] 2017-08-04 12:20
Furthermore `pkg-config --libs urdfdom` output: 

    root@e8a3559575dd:~/dependencies/bolero-dev/control/urdfdom/build# pkg-config --libs urdfdom
    -L/root/dependencies/bolero-dev/install/lib -lurdfdom_sensor -lurdfdom_model_state -lurdfdom_model -lurdfdom_world -l -lbase-logging

**Comment by HWiese1980** [comment] 2017-08-04 12:24
I've installed ROS by 

    apt-get install ros-kinetic-desktop-full ros-kinetic-rqt* python-catkin-tools

**Comment by HWiese1980** [comment] 2017-08-04 12:26
control_urdfdom_build.txt: https://pastebin.com/Qx7faTzj

**Comment by AlexanderFabisch** [comment] 2017-08-04 14:06
I don't have a solution for this problem. Unfortunately ROS installs `urdfdom_headers` from the Ubuntu packages located in `/usr/include/`. There are some other dependencies that are also located in this folder (boost, tinyxml) so I cannot remove the directory from the include directories.

My recommendation for the moment would be to install ROS after BOLeRo.

Let me know if you have an idea for a better solution.

**Comment by HWiese1980** [comment] 2017-08-04 14:15
Hmm... I see... okay... so first BOLeRo and MARS and ROS afterwards... not that beautiful, actually, but well, so be it...

**Comment by HWiese1980** [comment] 2017-08-04 14:15
I'll leave the issue open, though. Maybe one day there will be a real solution.

**Comment by HWiese1980** [comment] 2017-08-07 07:19
Hmm... just thinking out loud... might it be possible to *rename* a package? Like that we have a *urdfdom_headers_for_bolero* package that is detached from the original *urdfdom_headers* and can be found individually by cmake?

That might be a solution. @AlexanderFabisch, what's your opinion?

In the long run I'll however recommend to update BOLeRo and ApproxIK to work with the upstream urdfdom_headers.

**Comment by AlexanderFabisch** [comment] 2017-08-07 08:32
Good idea. I think this will not be a solution for BOLeRo but it will be a solution for approxik. BOLeRo actually does not depend on ROS' `urdfdom_headers`. It is a fork of `urdfdom_headers` for Rock. I think we cannot do anything here. But you should talk to @malter about that issue. For approxik it is a good solution. Actually, I don't plan to upgrade to a recent version of `urdfdom_headers` there because I want to keep the maintenance cost low. I would actually rather integrate all the dependencies directly in approxik.

**Comment by malter** [comment] 2017-08-07 09:38
The urdfdom_headers are a dependency of MARS to load smurf files. For MARS we used a fork because there was much development going on on the master repositories of the urdfdom packages and that required a lot of maintenance. Currently, MARS should run with the fork and the original master version. So MARS should also run with the apt-get version, but I don't have the time and environment to test that right now. Also, I don't know what the state in ROCK is and how autoproj deals with the ROS installation.
You could try to add the urdfdom libraries (control/urdfdom, base/console_bridge and control/urdfdom_headers) to the ignore list in pybob/overrides.py line 200. If pkg-config finds the ros urdfdom package it might work.

**Comment by AlexanderFabisch** [comment] 2017-08-07 10:00
OK, I was misinformed there. :) The problem is that MARS does not build with the current Ubuntu version of urdfdom_headers. Could you maybe post again the error @HWiese1980 ?

**Comment by AlexanderFabisch** [comment] 2017-08-07 11:58
OK, should be fixed for approxik now @HWiese1980 .

**Comment by HWiese1980** [comment] 2017-08-08 04:56
- [ ] Test ApproxIK installation
- [ ] Post error message again

**Comment by AlexanderFabisch** [comment] 2017-08-30 15:48
I just fixed a bug that might be related to this issue in pybob: https://github.com/rock-simulation/pybob/commit/b2b823960d40a05db821febb5cb77d82786885c3

**Comment by AlexanderFabisch** [comment] 2019-11-05 19:58
I will close this since it is not really related to BOLeRo. It is a problem of MARS.

**Closed by AlexanderFabisch** 2019-11-05 19:58 UTC
Labels: build / installation
